import { fireEvent, render, screen } from '@testing-library/react'; import { MemoryRouter, Route, Routes } from 'react-router-dom'; import { describe, expect, it, vi } from 'vitest'; import { AxiosError, type AxiosResponse } from 'axios'
import { Badge, Button } from '../components/ui'; import { hasPermission } from '../lib/permissions'; import type { TenantContext, User } from '../types/auth'; import { AuthContext } from '../contexts/AuthContext'; import { ModulePermissionRoute, ProtectedRoute } from '../routes/AppRoutes'; import { AppLayout } from '../layouts/AppLayout'; import { isSessionError } from '../services/api'; import { customersApi } from '../services/customers'; import { vehiclesApi } from '../services/vehicles'
describe('design system',()=>{it('renderiza botao com altura padrao',()=>{render(<Button>Salvar</Button>);expect(screen.getByRole('button')).toHaveClass('h-10')});it('renderiza status acessivel',()=>{render(<Badge tone="success">Concluido</Badge>);expect(screen.getByText('Concluido')).toBeInTheDocument()})})
describe('permissoes',()=>{const user:User={id:'1',name:'Teste',email:'teste@movencar.demo',role:'Gestor',permissions:['dashboard.view']};it('libera permissao atribuida',()=>expect(hasPermission(user,'dashboard.view')).toBe(true));it('nega permissao ausente',()=>expect(hasPermission(user,'finance.view')).toBe(false));it('nega usuario ausente',()=>expect(hasPermission(null,'dashboard.view')).toBe(false))})
describe('router baseline',()=>{it('mantem links navegaveis',()=>{render(<MemoryRouter><a href="/agenda">Agenda</a></MemoryRouter>);expect(screen.getByRole('link')).toHaveAttribute('href','/agenda')})})
const tenant:TenantContext={companyId:'1',companyName:'Oficina Teste',branchId:'matriz',branchName:'Matriz',enabledModules:['core','customers','vehicles','workshop','finance','crm','yard','tools-assets']}
const auth=(user:User|null)=>({user,tenant,authenticated:Boolean(user),login:vi.fn(),logout:vi.fn(),setBranch:vi.fn()})
describe('protecao e layout',()=>{it('redireciona visitante para login',()=>{render(<AuthContext.Provider value={auth(null)}><MemoryRouter initialEntries={['/privado']}><Routes><Route path="/login" element={<div>Login seguro</div>}/><Route path="/privado" element={<ProtectedRoute><div>Privado</div></ProtectedRoute>}/></Routes></MemoryRouter></AuthContext.Provider>);expect(screen.getByText('Login seguro')).toBeInTheDocument()});it('renderiza layout e abre sidebar mobile',()=>{const user:User={id:'1',name:'Teste',email:'t@t.com',role:'Administrador',permissions:['dashboard.view']};render(<AuthContext.Provider value={auth(user)}><MemoryRouter><Routes><Route element={<AppLayout/>}><Route index element={<div>Conteudo</div>}/></Route></Routes></MemoryRouter></AuthContext.Provider>);expect(screen.getByText('Conteudo')).toBeInTheDocument();fireEvent.click(screen.getByLabelText('Abrir menu'));expect(screen.getAllByAltText('MovenCar').length).toBeGreaterThan(1)})})
describe('feature gating frontend',()=>{it('bloqueia rota direta quando o modulo esta indisponivel',()=>{const user:User={id:'1',name:'Teste',email:'t@t.com',role:'Administrador',permissions:['vehicle_history.view']};const unavailable={...tenant,enabledModules:['core','customers']};render(<AuthContext.Provider value={{...auth(user),tenant:unavailable}}><MemoryRouter initialEntries={['/historico']}><Routes><Route path="/historico" element={<ModulePermissionRoute p="vehicle_history.view"><div>Timeline</div></ModulePermissionRoute>}/><Route path="/sem-acesso" element={<div>Modulo bloqueado</div>}/></Routes></MemoryRouter></AuthContext.Provider>);expect(screen.getByText('Modulo bloqueado')).toBeInTheDocument();expect(screen.queryByText('Timeline')).not.toBeInTheDocument()});it('esconde item do menu mesmo quando o usuario possui permissao',()=>{const user:User={id:'1',name:'Teste',email:'t@t.com',role:'Administrador',permissions:['vehicles.view']};const unavailable={...tenant,enabledModules:['core','customers']};render(<AuthContext.Provider value={{...auth(user),tenant:unavailable}}><MemoryRouter><Routes><Route element={<AppLayout/>}><Route index element={<div>Conteudo modular</div>}/></Route></Routes></MemoryRouter></AuthContext.Provider>);expect(screen.queryByText('Veiculos')).not.toBeInTheDocument()})})
describe('sessao revogada',()=>{it('reconhece status de sessao invalida',()=>{const response={status:419} as AxiosResponse;expect(isSessionError(new AxiosError('expirada',undefined,undefined,undefined,response))).toBe(true)})})
describe('clientes demonstrativos',()=>{it('preserva o modo mock sem chamar a API autenticada',async()=>{const created=await customersApi.create({name:'Cliente Mock Seguro',type:'INDIVIDUAL',document:'987.654.321-00'});const listed=await customersApi.list({page:1,limit:20,search:'98765432100'});expect(listed.data.map(customer=>customer.id)).toContain(created.id);await customersApi.remove(created.id)})})
describe('veiculos demonstrativos',()=>{it('normaliza placa e preserva o modo mock',async()=>{const created=await vehiclesApi.create({customerId:'demo-customer-1',brand:'Fiat',model:'Uno',plate:'abc-1234'});expect(created.plate).toBe('ABC1234');const listed=await vehiclesApi.list({page:1,limit:20,search:'ABC-1234'});expect(listed.data.map(vehicle=>vehicle.id)).toContain(created.id);await vehiclesApi.remove(created.id)})})
