import { Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { AppLayout } from '../layouts/AppLayout'; import { useAuth } from '../hooks/useAuth'; import { hasPermission } from '../lib/permissions'; import type { Permission } from '../types/auth'
import { LoginPage } from '../pages/LoginPage'; import { DashboardPage } from '../pages/DashboardPage'; import { AgendaPage } from '../pages/AgendaPage'; import { FinancePage } from '../pages/FinancePage'; import { ListPage } from '../pages/ListPage'; import { SessionEndedPage } from '../pages/SessionEndedPage'
import { CustomersPage } from '../pages/CustomersPage'
import { VehiclesPage } from '../pages/VehiclesPage'
import { hasModule,moduleForPermission } from '../lib/moduleAccess'
export function ProtectedRoute({children}:{children:React.ReactNode}){const {authenticated,initializing}=useAuth(); const loc=useLocation(); if(initializing)return <div className="grid min-h-screen place-items-center bg-canvas text-sm text-slate-500">Carregando sessao...</div>; return authenticated?<>{children}</>:<Navigate to="/login" state={{from:loc.pathname}} replace/>}
export function PermissionRoute({permission,children}:{permission:Permission;children:React.ReactNode}){const {user}=useAuth(); return hasPermission(user,permission)?<>{children}</>:<Navigate to="/sem-acesso" replace/>}
const Guard=({p,children}:{p:Permission;children:React.ReactNode})=>{const{tenant}=useAuth();return hasModule(tenant,moduleForPermission(p))?<PermissionRoute permission={p}>{children}</PermissionRoute>:<Navigate to="/sem-acesso" replace/>}
export function AppRoutes(){return <Routes><Route path="/login" element={<LoginPage/>}/><Route path="/sessao-encerrada" element={<SessionEndedPage/>}/><Route element={<ProtectedRoute><AppLayout/></ProtectedRoute>}><Route index element={<Guard p="dashboard.view"><DashboardPage/></Guard>}/><Route path="agenda" element={<Guard p="agenda.view"><AgendaPage/></Guard>}/><Route path="veiculos" element={<Guard p="vehicles.view"><VehiclesPage/></Guard>}/><Route path="ordens-servico" element={<Guard p="orders.view"><ListPage title="Ordens de servico" description="Do orcamento a entrega do veiculo" action="Nova ordem"/></Guard>}/><Route path="financeiro" element={<Guard p="finance.view"><FinancePage/></Guard>}/><Route path="clientes" element={<Guard p="customers.view"><CustomersPage/></Guard>}/><Route path="crm" element={<Navigate to="/clientes" replace/>}/><Route path="patio" element={<Guard p="yard.view"><ListPage title="Patio" description="Localizacao e situacao de cada veiculo" action="Registrar entrada"/></Guard>}/><Route path="ferramentas" element={<Guard p="tools.view"><ListPage title="Ferramentas" description="Emprestimos, manutencoes e inventario" action="Nova ferramenta"/></Guard>}/><Route path="centros-custo" element={<Guard p="finance.view"><ListPage title="Centros de custo" description="Distribuicao gerencial de despesas e receitas" action="Novo centro"/></Guard>}/><Route path="avaliacoes" element={<Guard p="crm.view"><ListPage title="Avaliacoes" description="Satisfacao, reputacao e planos de recuperacao" empty/></Guard>}/><Route path="checklists" element={<Guard p="orders.view"><ListPage title="Modelos de checklist" description="Padronize inspecoes e entregas" action="Novo modelo"/></Guard>}/><Route path="configuracoes" element={<Guard p="settings.manage"><ListPage title="Configuracoes" description="Empresa, filiais, usuarios e integracoes" action="Convidar usuario"/></Guard>}/><Route path="sem-acesso" element={<ListPage title="Acesso restrito" description="Seu perfil nao possui permissao para este modulo" empty/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
