import { beforeEach,describe,expect,it,vi } from 'vitest'

const db=vi.hoisted(()=>({companyModule:{findMany:vi.fn()}}))
vi.mock('../src/lib/prisma.js',()=>({prisma:db}))
import { listEnabledModules,requireModule } from '../src/modules/platform/module-gate.js'
import { requirePermission } from '../src/modules/auth/auth.middleware.js'

describe('company module gate',()=>{
  beforeEach(()=>vi.clearAllMocks())
  it('lists only active, non-expired modules for the authenticated company',async()=>{db.companyModule.findMany.mockResolvedValue([{module:{code:'customers'}},{module:{code:'vehicles'}}]);await expect(listEnabledModules('company-a',new Date('2026-08-07T12:00:00Z'))).resolves.toEqual(['customers','vehicles']);expect(db.companyModule.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({companyId:'company-a',status:'ACTIVE',module:{status:'ACTIVE'}})}))})
  it('allows vehicles only when both vehicles and customers are active',async()=>{db.companyModule.findMany.mockResolvedValue([{module:{code:'vehicles'}},{module:{code:'customers'}}]);const next=vi.fn();await requireModule('vehicles')({auth:{companyId:'company-a'}} as any,{} as any,next);expect(next).toHaveBeenCalledWith();expect(db.companyModule.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({companyId:'company-a',status:'ACTIVE',module:{code:{in:['vehicles','customers']},status:'ACTIVE'}})}))})
  it('still requires user permission after the company module passes',async()=>{db.companyModule.findMany.mockResolvedValue([{module:{code:'customers'}}]);const moduleNext=vi.fn();const req={auth:{companyId:'company-a',permissions:[]}} as any;await requireModule('customers')(req,{} as any,moduleNext);expect(moduleNext).toHaveBeenCalledWith();const permissionNext=vi.fn();requirePermission('customers.view')(req,{} as any,permissionNext);expect(permissionNext.mock.calls[0][0]).toMatchObject({status:403,code:'FORBIDDEN'})})
  it('allows the action when module and permission are both present',async()=>{db.companyModule.findMany.mockResolvedValue([{module:{code:'customers'}}]);const req={auth:{companyId:'company-a',permissions:['customers.view']}} as any;const moduleNext=vi.fn();await requireModule('customers')(req,{} as any,moduleNext);expect(moduleNext).toHaveBeenCalledWith();const permissionNext=vi.fn();requirePermission('customers.view')(req,{} as any,permissionNext);expect(permissionNext).toHaveBeenCalledWith()})
  it('blocks a company without the module even if a permission could exist',async()=>{db.companyModule.findMany.mockResolvedValue([]);const next=vi.fn();await requireModule('fiscal')({auth:{companyId:'company-a',permissions:['invoices.create']}} as any,{} as any,next);expect(next.mock.calls[0][0]).toMatchObject({status:403,code:'MODULE_NOT_AVAILABLE'})})
  it.each(['INACTIVE','SUSPENDED','EXPIRED'])('blocks a %s company module through the ACTIVE query',async status=>{db.companyModule.findMany.mockResolvedValue([]);const next=vi.fn();await requireModule('customers')({auth:{companyId:'company-a'}} as any,{} as any,next);expect(next.mock.calls[0][0]).toMatchObject({code:'MODULE_NOT_AVAILABLE'});expect(db.companyModule.findMany.mock.calls[0][0].where.status).toBe('ACTIVE');expect(status).not.toBe('ACTIVE')})
  it('blocks vehicles when its customers dependency is unavailable',async()=>{db.companyModule.findMany.mockResolvedValue([{module:{code:'vehicles'}}]);const next=vi.fn();await requireModule('vehicles')({auth:{companyId:'company-a'}} as any,{} as any,next);expect(next.mock.calls[0][0]).toMatchObject({code:'MODULE_NOT_AVAILABLE'})})
  it('never queries another company while authorizing the current tenant',async()=>{db.companyModule.findMany.mockResolvedValue([]);const next=vi.fn();await requireModule('vehicles')({auth:{companyId:'company-b'}} as any,{} as any,next);expect(db.companyModule.findMany.mock.calls[0][0].where.companyId).toBe('company-b')})
})
