import { beforeEach,describe,expect,it,vi } from 'vitest'
const db=vi.hoisted(()=>({vehicle:{findFirst:vi.fn(),updateMany:vi.fn(),findFirstOrThrow:vi.fn(),create:vi.fn()},customer:{findFirst:vi.fn()},branch:{findFirst:vi.fn()},auditLog:{create:vi.fn()},$transaction:vi.fn()}))
vi.mock('../src/lib/prisma.js',()=>({prisma:db}))
import { createVehicle,deleteVehicle,updateVehicle,type VehicleActor } from '../src/modules/vehicles/vehicles.service.js'
const actor:VehicleActor={companyId:'company-a',branchId:'branch-a',userId:'user-a'}
describe('vehicle service tenant enforcement',()=>{beforeEach(()=>{vi.clearAllMocks();db.$transaction.mockImplementation(async(callback:(tx:typeof db)=>unknown)=>callback(db))})
it('derives companyId from the actor when creating',async()=>{db.customer.findFirst.mockResolvedValue({id:'customer-a'});db.vehicle.create.mockResolvedValue({id:'vehicle-a',customerId:'customer-a',plate:'ABC1234'});await createVehicle(actor,{customerId:'customer-a',brand:'VW',model:'Gol',status:'ACTIVE',plate:'ABC1234'});expect(db.vehicle.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({companyId:'company-a',customerId:'customer-a'})}))})
it('uses an explicit response selection without tenant or soft-delete internals',async()=>{db.customer.findFirst.mockResolvedValue({id:'customer-a'});db.vehicle.create.mockResolvedValue({id:'vehicle-a',customerId:'customer-a',plate:null});await createVehicle(actor,{customerId:'customer-a',brand:'VW',model:'Gol',status:'ACTIVE'});const select=db.vehicle.create.mock.calls[0][0].select;expect(select.companyId).toBeUndefined();expect(select.deletedAt).toBeUndefined()})
it('rejects linking another tenant customer before create',async()=>{db.customer.findFirst.mockResolvedValue(null);await expect(createVehicle(actor,{customerId:'customer-b',brand:'VW',model:'Gol',status:'ACTIVE'})).rejects.toMatchObject({status:404,code:'CUSTOMER_NOT_FOUND'});expect(db.vehicle.create).not.toHaveBeenCalled()})
it('rejects linking a branch from another tenant',async()=>{db.customer.findFirst.mockResolvedValue({id:'customer-a'});db.branch.findFirst.mockResolvedValue(null);await expect(createVehicle(actor,{customerId:'customer-a',originBranchId:'branch-b',brand:'VW',model:'Gol',status:'ACTIVE'})).rejects.toMatchObject({status:404,code:'BRANCH_NOT_FOUND'});expect(db.vehicle.create).not.toHaveBeenCalled()})
it('writes updates with id, companyId and active-row filter',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a'});db.vehicle.updateMany.mockResolvedValue({count:1});db.vehicle.findFirstOrThrow.mockResolvedValue({id:'vehicle-a'});await updateVehicle(actor,'vehicle-a',{model:'Polo'});expect(db.vehicle.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:'vehicle-a',companyId:'company-a',deletedAt:null}}))})
it('soft deletes with tenant filter and INACTIVE status',async()=>{db.vehicle.updateMany.mockResolvedValue({count:1});await deleteVehicle(actor,'vehicle-a');expect(db.vehicle.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:'vehicle-a',companyId:'company-a',deletedAt:null},data:expect.objectContaining({status:'INACTIVE',deletedAt:expect.any(Date)})}))})})
