import { beforeEach,describe,expect,it,vi } from 'vitest'
const db=vi.hoisted(()=>({vehicle:{findFirst:vi.fn(),findMany:vi.fn(),count:vi.fn(),updateMany:vi.fn(),findFirstOrThrow:vi.fn(),create:vi.fn()},vehicleHistoryEvent:{create:vi.fn()},customer:{findFirst:vi.fn()},branch:{findFirst:vi.fn()},auditLog:{create:vi.fn()},$transaction:vi.fn()}))
vi.mock('../src/lib/prisma.js',()=>({prisma:db}))
import { createVehicle,deleteVehicle,getVehicle,listVehicles,updateVehicle,type VehicleActor } from '../src/modules/vehicles/vehicles.service.js'
const actor:VehicleActor={companyId:'company-a',branchId:'branch-a',userId:'user-a'}
describe('vehicle service tenant enforcement',()=>{beforeEach(()=>{vi.clearAllMocks();db.vehicleHistoryEvent.create.mockResolvedValue({id:'history-a'});db.$transaction.mockImplementation(async(input:((tx:typeof db)=>unknown)|unknown[])=>Array.isArray(input)?Promise.all(input):input(db))})
it('keeps list and customer filter scoped to the authenticated company',async()=>{db.vehicle.findMany.mockResolvedValue([]);db.vehicle.count.mockResolvedValue(0);await listVehicles('company-a',{page:1,limit:20,customerId:'customer-b',sortBy:'createdAt',sortOrder:'desc'});expect(db.vehicle.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({companyId:'company-a',customerId:'customer-b',deletedAt:null})}))})
it('reads a vehicle only by id, companyId and active-row filter',async()=>{db.vehicle.findFirst.mockResolvedValue(null);await expect(getVehicle('company-b','vehicle-a')).rejects.toMatchObject({status:404,code:'VEHICLE_NOT_FOUND'});expect(db.vehicle.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:{id:'vehicle-a',companyId:'company-b',deletedAt:null}}))})
it('derives companyId from the actor when creating',async()=>{db.customer.findFirst.mockResolvedValue({id:'customer-a'});db.vehicle.create.mockResolvedValue({id:'vehicle-a',customerId:'customer-a',plate:'ABC1234'});await createVehicle(actor,{customerId:'customer-a',brand:'VW',model:'Gol',status:'ACTIVE',plate:'ABC1234'});expect(db.vehicle.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({companyId:'company-a',customerId:'customer-a'})}))})
it('uses an explicit response selection without tenant or soft-delete internals',async()=>{db.customer.findFirst.mockResolvedValue({id:'customer-a'});db.vehicle.create.mockResolvedValue({id:'vehicle-a',customerId:'customer-a',plate:null});await createVehicle(actor,{customerId:'customer-a',brand:'VW',model:'Gol',status:'ACTIVE'});const select=db.vehicle.create.mock.calls[0][0].select;expect(select.companyId).toBeUndefined();expect(select.deletedAt).toBeUndefined()})
it('rejects linking another tenant customer before create',async()=>{db.customer.findFirst.mockResolvedValue(null);await expect(createVehicle(actor,{customerId:'customer-b',brand:'VW',model:'Gol',status:'ACTIVE'})).rejects.toMatchObject({status:404,code:'CUSTOMER_NOT_FOUND'});expect(db.vehicle.create).not.toHaveBeenCalled()})
it('rejects linking a branch from another tenant',async()=>{db.customer.findFirst.mockResolvedValue({id:'customer-a'});db.branch.findFirst.mockResolvedValue(null);await expect(createVehicle(actor,{customerId:'customer-a',originBranchId:'branch-b',brand:'VW',model:'Gol',status:'ACTIVE'})).rejects.toMatchObject({status:404,code:'BRANCH_NOT_FOUND'});expect(db.vehicle.create).not.toHaveBeenCalled()})
it('writes updates with id, companyId and active-row filter',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a'});db.vehicle.updateMany.mockResolvedValue({count:1});db.vehicle.findFirstOrThrow.mockResolvedValue({id:'vehicle-a'});await updateVehicle(actor,'vehicle-a',{model:'Polo'});expect(db.vehicle.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:'vehicle-a',companyId:'company-a',deletedAt:null}}))})
it('rejects reducing the current mileage',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a',currentMileage:50000});await expect(updateVehicle(actor,'vehicle-a',{currentMileage:49000})).rejects.toMatchObject({status:400,code:'VEHICLE_MILEAGE_DECREASE'});expect(db.vehicle.updateMany).not.toHaveBeenCalled();expect(db.vehicleHistoryEvent.create).not.toHaveBeenCalled()})
it('soft deletes with tenant filter and INACTIVE status',async()=>{db.vehicle.updateMany.mockResolvedValue({count:1});await deleteVehicle(actor,'vehicle-a');expect(db.vehicle.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:'vehicle-a',companyId:'company-a',deletedAt:null},data:expect.objectContaining({status:'INACTIVE',deletedAt:expect.any(Date)})}))})})
