import { beforeEach,describe,expect,it,vi } from 'vitest'
const db=vi.hoisted(()=>({vehicle:{findFirst:vi.fn(),updateMany:vi.fn()},vehicleHistoryEvent:{findMany:vi.fn(),count:vi.fn(),findFirst:vi.fn(),create:vi.fn()},branch:{findFirst:vi.fn()},auditLog:{create:vi.fn()},$transaction:vi.fn()}))
vi.mock('../src/lib/prisma.js',()=>({prisma:db}))
import { createManualHistory,getHistoryEvent,listHistory,type HistoryActor } from '../src/modules/vehicle-history/vehicle-history.service.js'
const actor:HistoryActor={companyId:'company-a',branchId:'branch-a',userId:'user-a'}
const listInput={page:1,limit:20,sortOrder:'desc' as const}
describe('vehicle history service security',()=>{beforeEach(()=>{vi.clearAllMocks();db.$transaction.mockImplementation(async(input:((tx:typeof db)=>unknown)|unknown[])=>Array.isArray(input)?Promise.all(input):input(db));db.vehicleHistoryEvent.create.mockResolvedValue({id:'event-a',vehicleId:'vehicle-a',eventType:'NOTE',mileage:null})})
it('lists with companyId, vehicleId, pagination and chronological order',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a'});db.vehicleHistoryEvent.findMany.mockResolvedValue([]);db.vehicleHistoryEvent.count.mockResolvedValue(0);await listHistory('company-a','vehicle-a',listInput);expect(db.vehicleHistoryEvent.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({companyId:'company-a',vehicleId:'vehicle-a'}),orderBy:[{eventDate:'desc'},{createdAt:'desc'}],skip:0,take:20}))})
it('applies event type and period filters',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a'});db.vehicleHistoryEvent.findMany.mockResolvedValue([]);db.vehicleHistoryEvent.count.mockResolvedValue(0);const dateFrom=new Date('2026-01-01');const dateTo=new Date('2026-02-01');await listHistory('company-a','vehicle-a',{...listInput,eventType:'NOTE',dateFrom,dateTo});expect(db.vehicleHistoryEvent.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({eventType:'NOTE',eventDate:{gte:dateFrom,lte:dateTo}})}))})
it('returns 404 before listing another tenant vehicle history',async()=>{db.vehicle.findFirst.mockResolvedValue(null);await expect(listHistory('company-b','vehicle-a',listInput)).rejects.toMatchObject({status:404,code:'VEHICLE_NOT_FOUND'});expect(db.vehicleHistoryEvent.findMany).not.toHaveBeenCalled()})
it('reads eventId with companyId and vehicleId',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a'});db.vehicleHistoryEvent.findFirst.mockResolvedValue(null);await expect(getHistoryEvent('company-a','vehicle-a','event-b')).rejects.toMatchObject({status:404});expect(db.vehicleHistoryEvent.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:{id:'event-b',vehicleId:'vehicle-a',companyId:'company-a'}}))})
it('derives company, actor and source from session data',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a',currentMileage:1000});db.branch.findFirst.mockResolvedValue({id:'branch-a'});await createManualHistory(actor,'vehicle-a',{title:'Nota',eventType:'NOTE'});expect(db.vehicleHistoryEvent.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({companyId:'company-a',vehicleId:'vehicle-a',actorUserId:'user-a',branchId:'branch-a',sourceType:'MANUAL',isManual:true})}))})
it('rejects a branch from another company',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a'});db.branch.findFirst.mockResolvedValue(null);await expect(createManualHistory(actor,'vehicle-a',{title:'Nota',eventType:'NOTE',branchId:'branch-b'})).rejects.toMatchObject({status:404,code:'BRANCH_NOT_FOUND'});expect(db.vehicleHistoryEvent.create).not.toHaveBeenCalled()})
it('raises mileage with a tenant-safe conditional update',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a',currentMileage:1000});db.branch.findFirst.mockResolvedValue({id:'branch-a'});db.vehicle.updateMany.mockResolvedValue({count:1});db.vehicleHistoryEvent.create.mockResolvedValue({id:'event-a',vehicleId:'vehicle-a',eventType:'MILEAGE_RECORDED',mileage:1500});await createManualHistory(actor,'vehicle-a',{title:'Km',eventType:'MILEAGE_RECORDED',mileage:1500});expect(db.vehicle.updateMany).toHaveBeenCalledWith({where:{id:'vehicle-a',companyId:'company-a',deletedAt:null,OR:[{currentMileage:null},{currentMileage:{lt:1500}}]},data:{currentMileage:1500}})})
it('records lower mileage without reducing the vehicle value',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a',currentMileage:2000});db.branch.findFirst.mockResolvedValue({id:'branch-a'});await createManualHistory(actor,'vehicle-a',{title:'Km anterior',eventType:'MILEAGE_RECORDED',mileage:1500});expect(db.vehicleHistoryEvent.create).toHaveBeenCalled();expect(db.vehicle.updateMany).not.toHaveBeenCalled()})
it('uses an explicit response select without company or metadata internals',async()=>{db.vehicle.findFirst.mockResolvedValue({id:'vehicle-a',currentMileage:null});db.branch.findFirst.mockResolvedValue({id:'branch-a'});await createManualHistory(actor,'vehicle-a',{title:'Nota',eventType:'NOTE'});const select=db.vehicleHistoryEvent.create.mock.calls[0][0].select;expect(select.companyId).toBeUndefined();expect(select.metadata).toBeUndefined()})})
