ALTER TYPE "CheckInDamageLocation"
ADD VALUE IF NOT EXISTS 'FRONT_LEFT_HEADLIGHT';

ALTER TYPE "CheckInDamageLocation"
ADD VALUE IF NOT EXISTS 'FRONT_RIGHT_HEADLIGHT';

ALTER TYPE "CheckInDamageLocation"
ADD VALUE IF NOT EXISTS 'REAR_LEFT_TAILLIGHT';

ALTER TYPE "CheckInDamageLocation"
ADD VALUE IF NOT EXISTS 'REAR_RIGHT_TAILLIGHT';
