import { ArrowRight, Boxes, CalendarClock, CarFront, CheckCircle2, Clock3, MessageCircle, PackageX, TrendingUp, UsersRound, Wrench } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { cn } from '../lib/cn'
import { Badge, Card, IconButton } from './ui'

export function DashboardKpiCard({title,value,comparison,icon:Icon,tone}:{title:string;value:string;comparison:string;icon:typeof CarFront;tone:'purple'|'lime'|'yellow'|'orange'|'green'}){return <button className="group min-w-0 rounded-xl border border-slate-200 bg-white p-3 text-left shadow-panel transition hover:-translate-y-0.5 hover:border-slate-300"><div className="flex items-start justify-between"><span className={cn('grid size-8 place-items-center rounded-lg',tone==='purple'&&'bg-purple-50 text-purple-500',tone==='lime'&&'bg-lime-50 text-lime-700',tone==='yellow'&&'bg-brand-50 text-brand-700',tone==='orange'&&'bg-orange-50 text-orange-600',tone==='green'&&'bg-emerald-50 text-emerald-600')}><Icon className="size-4"/></span><TrendingUp className="size-3.5 text-emerald-500"/></div><p className="mt-3 truncate text-[11px] font-semibold uppercase text-slate-500">{title}</p><div className="mt-1 flex items-end justify-between gap-2"><strong className="text-[25px] leading-none text-slate-900">{value}</strong><span className="truncate text-[10px] text-emerald-600">{comparison}</span></div></button>}
export function DashboardSection({title,helper,action,children,className}:{title:string;helper?:string;action?:string;children:React.ReactNode;className?:string}){return <Card className={cn('min-w-0 overflow-hidden rounded-xl',className)}><header className="flex h-12 items-center justify-between border-b border-slate-100 px-4"><div className="min-w-0"><h2 className="truncate text-[15px] font-bold">{title}</h2>{helper&&<p className="truncate text-[10px] text-slate-400">{helper}</p>}</div>{action&&<button className="flex shrink-0 items-center gap-1 text-[11px] font-semibold text-purple-700 hover:text-purple-500">{action}<ArrowRight className="size-3"/></button>}</header>{children}</Card>}
const kanban=[{title:'Diagnostico',tone:'purple',items:[['OS-1844','Andre Lima','Ford Ka 2019','RJP-4A12','Lucas'],['OS-1843','Ana Reis','Fiat Argo 2021','BXT-8J91','Marcos']]},{title:'Aprovacao',tone:'yellow',items:[['OS-1841','Paula Nunes','Jeep Renegade','GHA-2K18','Carlos']]},{title:'Em execucao',tone:'lime',items:[['OS-1842','Rafael Almeida','Honda Civic 2020','KLP-9D20','Diego'],['OS-1839','Beatriz Lima','Toyota Corolla','FTR-1C62','Lucas']]},{title:'Pronto p/ entrega',tone:'green',items:[['OS-1840','Carlos Souza','VW T-Cross 2021','MNO-7B44','Marcos']]}]
export function MiniKanban(){return <div className="grid gap-2 p-3 sm:grid-cols-2 xl:grid-cols-4">{kanban.map(col=><div key={col.title} className="min-w-0 rounded-lg bg-slate-50 p-2"><div className="mb-2 flex items-center justify-between"><strong className="text-[11px] uppercase text-slate-600">{col.title}</strong><Badge tone={col.tone==='green'?'success':col.tone==='yellow'?'warning':col.tone==='purple'?'info':'neutral'}>{col.items.length}</Badge></div><div className="space-y-2">{col.items.slice(0,3).map(item=><button key={item[0]} className="w-full rounded-lg border bg-white p-2 text-left hover:border-purple-300"><div className="flex justify-between"><strong className="text-[11px] text-purple-700">{item[0]}</strong><span className="text-[9px] text-slate-400">{item[3]}</span></div><p className="mt-1 truncate text-[11px] font-semibold">{item[2]}</p><p className="truncate text-[10px] text-slate-500">{item[1]} · {item[4]}</p></button>)}</div></div>)}</div>}
const agenda=[['08:00','Revisao 40 mil km','Honda Civic','KLP-9D20','Rafael Almeida','Diego','Em atendimento'],['10:30','Diagnostico eletrico','Jeep Renegade','GHA-2K18','Paula Nunes','Carlos','Confirmado'],['14:00','Troca de oleo','VW T-Cross','MNO-7B44','Carlos Souza','Marcos','Agendado'],['16:30','Suspensao','Toyota Corolla','FTR-1C62','Beatriz Lima','Lucas','Agendado']]
export function DailyAgenda(){return <div className="divide-y divide-slate-100">{agenda.map(item=><div key={item[0]} className="grid grid-cols-[42px_1fr_auto] gap-2 px-3 py-2"><strong className="text-xs text-purple-700">{item[0]}</strong><div className="min-w-0"><p className="truncate text-[11px] font-semibold">{item[1]}</p><p className="truncate text-[10px] text-slate-500">{item[2]} · {item[3]} · {item[5]}</p></div><Badge tone={item[6]==='Em atendimento'?'success':'neutral'}>{item[6]}</Badge></div>)}</div>}
const movements=[['08:12','Entrada','Honda Civic','KLP-9D20','Rafael Almeida'],['09:05','Entrada','Ford Ka','RJP-4A12','Andre Lima'],['11:40','Saida','VW T-Cross','MNO-7B44','Carlos Souza'],['15:20','Prevista','Toyota Corolla','FTR-1C62','Beatriz Lima']]
export function VehicleMovementList(){return <div className="divide-y divide-slate-100">{movements.map((item)=><div key={item[0]} className="flex items-center gap-2 px-3 py-2"><span className="w-10 text-xs font-bold text-slate-700">{item[0]}</span><span className={cn('size-2 rounded-full',item[1]==='Entrada'?'bg-lime-500':item[1]==='Saida'?'bg-purple-500':'bg-brand-500')}/><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold">{item[2]} · {item[3]}</p><p className="truncate text-[10px] text-slate-500">{item[4]}</p></div><span className="text-[10px] text-slate-500">{item[1]}</span></div>)}</div>}
export function CompactTable(){const rows=[['OS-1842','Rafael Almeida','Honda Civic','KLP-9D20','Em execucao','R$ 2.480','Diego'],['OS-1841','Paula Nunes','Jeep Renegade','GHA-2K18','Aguardando','R$ 890','Carlos'],['OS-1840','Carlos Souza','VW T-Cross','MNO-7B44','Finalizada','R$ 540','Marcos'],['OS-1839','Beatriz Lima','Toyota Corolla','FTR-1C62','Orcamento','R$ 1.760','Lucas']];return <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-[11px]"><thead className="bg-slate-50 text-[9px] uppercase text-slate-500"><tr>{['OS','Cliente','Veiculo / placa','Status','Valor','Mecanico',''].map(h=><th className="px-3 py-2" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r[0]} className="hover:bg-slate-50"><td className="px-3 py-2 font-bold text-purple-700">{r[0]}</td><td className="px-3 py-2">{r[1]}</td><td className="px-3 py-2"><strong>{r[2]}</strong><br/><span className="text-[9px] text-slate-400">{r[3]}</span></td><td className="px-3 py-2"><Badge tone={r[4]==='Finalizada'?'success':r[4]==='Aguardando'?'warning':'neutral'}>{r[4]}</Badge></td><td className="px-3 py-2 font-semibold">{r[5]}</td><td className="px-3 py-2">{r[6]}</td><td><IconButton label="Abrir ordem" className="size-8 border-0"><ArrowRight className="size-3"/></IconButton></td></tr>)}</tbody></table></div>}
export function LowStockList(){return <div className="divide-y">{[['Pastilha de freio','PF-034','2','8'],['Oleo 5W30','OL-530','4','12'],['Filtro de ar','FA-112','1','5'],['Fluido DOT4','FD-004','3','6'],['Lampada H7','LP-H07','2','6']].map(i=><div key={i[1]} className="grid grid-cols-[1fr_auto] gap-2 px-3 py-2"><div className="min-w-0"><p className="truncate text-[11px] font-semibold">{i[0]}</p><p className="text-[9px] text-slate-400">{i[1]} · minimo {i[3]}</p></div><Badge tone="danger">{i[2]} un.</Badge></div>)}</div>}
export function CustomerReturnList(){return <div className="divide-y">{[['Juliana Alves','Chevrolet Onix','12/06','Revisao semestral'],['Mateus Rocha','Hyundai HB20','21/05','Troca de oleo'],['Renata Dias','Nissan Kicks','08/04','Inspecao de freios']].map(i=><div key={i[0]} className="flex items-center gap-2 px-3 py-2"><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold">{i[0]} · {i[1]}</p><p className="truncate text-[9px] text-slate-400">Ultima visita {i[2]} · {i[3]}</p></div><IconButton label={`WhatsApp de ${i[0]}`} className="size-8 border-emerald-200 text-emerald-600"><MessageCircle className="size-3.5"/></IconButton></div>)}</div>}
const revenue=[{month:'Mar',value:82400},{month:'Abr',value:96300},{month:'Mai',value:91800},{month:'Jun',value:108200},{month:'Jul',value:116400},{month:'Ago',value:128450}]
export function RevenueChart(){return <div className="h-48 p-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={revenue} margin={{top:5,right:5,left:-15,bottom:0}}><CartesianGrid stroke="#E2E8F0" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={9} tickFormatter={v=>`${v/1000}k`}/><Tooltip formatter={v=>`R$ ${Number(v).toLocaleString('pt-BR')}`}/><Bar dataKey="value" fill="#7C3AED" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div>}
// eslint-disable-next-line react-refresh/only-export-components
export const kpis=[{title:'Veiculos na oficina',value:'24',comparison:'+8,3%',icon:CarFront,tone:'purple' as const},{title:'Ordens em andamento',value:'14',comparison:'+12,0%',icon:Wrench,tone:'lime' as const},{title:'Aguardando aprovacao',value:'7',comparison:'-2 hoje',icon:Clock3,tone:'yellow' as const},{title:'Aguardando pecas',value:'5',comparison:'+1 hoje',icon:PackageX,tone:'orange' as const},{title:'Faturamento do mes',value:'R$ 128k',comparison:'+12,8%',icon:TrendingUp,tone:'green' as const},{title:'Clientes ativos',value:'1.284',comparison:'+4,6%',icon:UsersRound,tone:'purple' as const}]
// eslint-disable-next-line react-refresh/only-export-components
export const purchases=[['PC-804','Auto Pecas Brasil','R$ 3.480','05/08','Em transporte'],['PC-803','Distribuidora Sul','R$ 1.220','03/08','Atrasado'],['PC-801','LubriMax','R$ 2.750','06/08','Confirmado']]
export function PurchaseList(){return <div className="divide-y">{purchases.map(p=><div key={p[0]} className="grid grid-cols-[1fr_auto] gap-2 px-3 py-2"><div><p className="text-[11px] font-semibold">{p[0]} · {p[1]}</p><p className="text-[9px] text-slate-400">Prazo {p[3]} · {p[2]}</p></div><Badge tone={p[4]==='Atrasado'?'danger':p[4]==='Confirmado'?'success':'info'}>{p[4]}</Badge></div>)}</div>}
export function Receivables(){return <div className="grid grid-cols-2 gap-px bg-slate-100">{[['Vencidas','R$ 3.280','text-red-600'],['Ate 7 dias','R$ 18.460','text-orange-600'],['Apos 7 dias','R$ 42.180','text-purple-700'],['Total previsto','R$ 63.920','text-emerald-600']].map(i=><div key={i[0]} className="bg-white p-3"><p className="text-[10px] text-slate-500">{i[0]}</p><strong className={cn('mt-1 block text-base',i[2])}>{i[1]}</strong></div>)}</div>}
// eslint-disable-next-line react-refresh/only-export-components
export const dashboardIcons={Boxes,CalendarClock,CheckCircle2}
